### Create a Multi-layer fully connected neural network with the following configuration of the hidden layers to classify the digits of the MNIST data base.
Hidden layers configuration:
- Hidden Layer 1 : 300
- Hidden layer 2 : 200
- Hidden layer 3: 100
- Hidden layer 4: 50
- Softmax layer : 10

Train and test the model and print the accuracy.

In [1]:
##Import tensorflow and other modules like numpy,pandas etc.
import tensorflow as tf
mnist=tf.keras.datasets.mnist

In [2]:
##Import Keras libraries:
from keras.models import Sequential
from keras.layers import Flatten
from keras.layers import Dense

Using TensorFlow backend.


In [3]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [4]:
x_train[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  42, 118,
        219, 166, 118, 118,   6,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 103, 242, 254,
        254, 254, 254, 254,  66,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [5]:
x_test[10]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  61,   3,
         42, 118, 193, 118, 118,  61,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14, 179, 245, 236,
        242, 254, 254, 254, 254, 245, 235,  84,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [6]:
y_train[10]

3

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
y_test[10]

0

In [9]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [10]:
#Normalizing the data
x_train=x_train/255.0
x_test=x_test/255.0

In [11]:
##Instantiating the model
mymodel=Sequential()

In [12]:
##Flattening
mymodel.add(Flatten(input_shape=(28,28)))

In [13]:
##creating a network:
mymodel.add(Dense(units=300,activation='relu'))
mymodel.add(Dense(units=200,activation='relu'))
mymodel.add(Dense(units=100,activation='relu'))
mymodel.add(Dense(units=50,activation='relu'))
mymodel.add(Dense(units=10,activation='softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [14]:
##Compiling
mymodel.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [15]:
##shows the structure or network layout
mymodel.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_2 (Dense)              (None, 200)               60200     
_________________________________________________________________
dense_3 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_4 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                510       
Total params: 321,360
Trainable params: 321,360
Non-trainable params: 0
________________________________________________

In [16]:
##fitting the model
mymodel.fit(x_train,y_train,epochs=10)


Epoch 1/10
60000/60000 [==============================] - 19s 317us/step - loss: 0.2158 - accuracy: 0.9358
Epoch 2/10
60000/60000 [==============================] - 17s 283us/step - loss: 0.0975 - accuracy: 0.9712
Epoch 3/10
60000/60000 [==============================] - 17s 283us/step - loss: 0.0698 - accuracy: 0.9787
Epoch 4/10
60000/60000 [==============================] - 19s 323us/step - loss: 0.0553 - accuracy: 0.9828
Epoch 5/10
60000/60000 [==============================] - 20s 342us/step - loss: 0.0439 - accuracy: 0.9865
Epoch 6/10
60000/60000 [==============================] - 19s 312us/step - loss: 0.0364 - accuracy: 0.9887
Epoch 7/10
60000/60000 [==============================] - 19s 317us/step - loss: 0.0317 - accuracy: 0.9901
Epoch 8/10
60000/60000 [==============================] - 20s 328us/step - loss: 0.0286 - accuracy: 0.9914
Epoch 9/10
60000/60000 [==============================] - 23s 386us/step - loss: 0.0254 - accuracy: 0.9924
Epoch 10/10
60000/60000 [===========

In [17]:
##Check the loss function and accuracy of the fitted model
mymodel.evaluate(x_test,y_test)

10000/10000 [==============================] - 1s 109us/step


[0.10039066469630416, 0.9776999950408936]

### Inference

In [18]:
test_image=x_test[110]

In [19]:
test_image.shape

(28, 28)

In [20]:
test_image1=test_image.reshape(1,28,28)

In [21]:
result=mymodel.predict(test_image1)
result

array([[1.7218003e-09, 1.0141924e-09, 3.0704477e-09, 4.0190740e-09,
        8.0840390e-11, 7.5364895e-11, 9.7971503e-14, 1.5621644e-10,
        1.0000000e+00, 4.7475552e-09]], dtype=float32)

In [22]:
result.argmax()

8

In [23]:
y_test[110]

8